mongo:
  enabled: false
  host: 127.0.0.1
  port: 27017
  authentication:
    database: main
    user: admin
    password: ""
redis:
  enabled: false
  host: 127.0.0.1
  port: 6379
  password: ""
server:
  name: dev-1